2023-09-14 17:06:06,097 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-09-14 17:06:06,097 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Configure stats pid to 127143
2023-09-14 17:06:06,097 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from /home/suyash/.config/wandb/settings
2023-09-14 17:06:06,097 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/settings
2023-09-14 17:06:06,097 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:_log_setup():524] Logging user logs to /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/run-20230914_170606-u0xuikae/logs/debug.log
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:_log_setup():525] Logging internal logs to /home/suyash/Desktop/IIIT/sem_5/ANLP/Ass2/ANLP-2/wandb/run-20230914_170606-u0xuikae/logs/debug-internal.log
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:init():564] calling init triggers
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:init():614] starting backend
2023-09-14 17:06:06,098 INFO    MainThread:127143 [wandb_init.py:init():618] setting up manager
2023-09-14 17:06:06,357 ERROR   MainThread:127143 [wandb_init.py:init():1193] error
Traceback (most recent call last):
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 619, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 37, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/suyash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
